// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("admins")]
    public partial class Admin
    {
        public Admin()
        {
            CustomerServiceCreatedByNavigations = new HashSet<CustomerService>();
            CustomerServiceEditedByNavigations = new HashSet<CustomerService>();
            InverseSupervisor = new HashSet<Admin>();
            LocationAddedByNavigations = new HashSet<Location>();
            LocationEditedByNavigations = new HashSet<Location>();
            PermissionCreatedByNavigations = new HashSet<Permission>();
            PermissionUpdatedByNavigations = new HashSet<Permission>();
            ProjectAddedByNavigations = new HashSet<Project>();
            ProjectDeletedByNavigations = new HashSet<Project>();
            ProjectEditedByNavigations = new HashSet<Project>();
            RoleCreatedByNavigations = new HashSet<Role>();
            RoleUpdatedByNavigations = new HashSet<Role>();
            Visitors = new HashSet<Visitor>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userName")]
        [StringLength(50)]
        public string UserName { get; set; }
        [Column("contactNameEn")]
        [StringLength(50)]
        public string ContactNameEn { get; set; }
        [Column("contactNameAr")]
        [StringLength(50)]
        public string ContactNameAr { get; set; }
        [Column("password")]
        [StringLength(100)]
        public string Password { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("isDeleted")]
        public bool? IsDeleted { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("groupPermission")]
        public short? GroupPermission { get; set; }
        [Column("createdBy")]
        public int? CreatedBy { get; set; }
        [Column("isSuperAdmin")]
        public bool? IsSuperAdmin { get; set; }
        [Column("profilePicture")]
        [StringLength(500)]
        public string ProfilePicture { get; set; }
        [Column("supervisorId")]
        public int? SupervisorId { get; set; }
        [Column("isSales")]
        public bool? IsSales { get; set; }
        [Column("roleId")]
        public int? RoleId { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("Admins")]
        public virtual Role Role { get; set; }
        [ForeignKey("SupervisorId")]
        [InverseProperty("InverseSupervisor")]
        public virtual Admin Supervisor { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<CustomerService> CustomerServiceCreatedByNavigations { get; set; }
        [InverseProperty("EditedByNavigation")]
        public virtual ICollection<CustomerService> CustomerServiceEditedByNavigations { get; set; }
        [InverseProperty("Supervisor")]
        public virtual ICollection<Admin> InverseSupervisor { get; set; }
        [InverseProperty("AddedByNavigation")]
        public virtual ICollection<Location> LocationAddedByNavigations { get; set; }
        [InverseProperty("EditedByNavigation")]
        public virtual ICollection<Location> LocationEditedByNavigations { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Permission> PermissionCreatedByNavigations { get; set; }
        [InverseProperty("UpdatedByNavigation")]
        public virtual ICollection<Permission> PermissionUpdatedByNavigations { get; set; }
        [InverseProperty("AddedByNavigation")]
        public virtual ICollection<Project> ProjectAddedByNavigations { get; set; }
        [InverseProperty("DeletedByNavigation")]
        public virtual ICollection<Project> ProjectDeletedByNavigations { get; set; }
        [InverseProperty("EditedByNavigation")]
        public virtual ICollection<Project> ProjectEditedByNavigations { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Role> RoleCreatedByNavigations { get; set; }
        [InverseProperty("UpdatedByNavigation")]
        public virtual ICollection<Role> RoleUpdatedByNavigations { get; set; }
        [InverseProperty("DeletedByNavigation")]
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}