// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("customerServices")]
    public partial class CustomerService
    {
        public CustomerService()
        {
            Locations = new HashSet<Location>();
            Visitors = new HashSet<Visitor>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userName")]
        [StringLength(50)]
        public string UserName { get; set; }
        [Column("contactNameEn")]
        [StringLength(50)]
        public string ContactNameEn { get; set; }
        [Column("contactNameAr")]
        [StringLength(50)]
        public string ContactNameAr { get; set; }
        [Column("phone")]
        [StringLength(50)]
        public string Phone { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("password")]
        [StringLength(100)]
        public string Password { get; set; }
        [Column("createdBy")]
        public int? CreatedBy { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("editedBy")]
        public int? EditedBy { get; set; }
        [Column("lastEditDate", TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
        [Column("isDeleted")]
        public bool? IsDeleted { get; set; }
        [Column("deletedBy")]
        public int? DeletedBy { get; set; }
        [Column("deletedAt", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("address")]
        [StringLength(50)]
        public string Address { get; set; }
        [Column("groupPermission")]
        public short? GroupPermission { get; set; }
        [Column("profilePicture")]
        [StringLength(500)]
        public string ProfilePicture { get; set; }
        [Column("insured")]
        public bool? Insured { get; set; }
        [Column("salary")]
        public int? Salary { get; set; }

        [ForeignKey("CreatedBy")]
        [InverseProperty("CustomerServiceCreatedByNavigations")]
        public virtual Admin CreatedByNavigation { get; set; }
        [ForeignKey("EditedBy")]
        [InverseProperty("CustomerServiceEditedByNavigations")]
        public virtual Admin EditedByNavigation { get; set; }
        [InverseProperty("DeletedyByNavigation")]
        public virtual ICollection<Location> Locations { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}