// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("locations")]
    public partial class Location
    {
        public Location()
        {
            LocationImages = new HashSet<LocationImage>();
            Reservations = new HashSet<Reservation>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("locationNameEn")]
        [StringLength(500)]
        public string LocationNameEn { get; set; }
        [Column("locationNameAr")]
        [StringLength(500)]
        public string LocationNameAr { get; set; }
        [Column("projectId")]
        public int? ProjectId { get; set; }
        [Column("price")]
        public double? Price { get; set; }
        [Column("area")]
        public double? Area { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("addedBy")]
        public int? AddedBy { get; set; }
        [Column("deletedAt", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("deletedyBy")]
        public int? DeletedyBy { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("paymentTypeId")]
        public int? PaymentTypeId { get; set; }
        [Column("locationTypeId")]
        public int? LocationTypeId { get; set; }
        [Column("withGarage")]
        public bool? WithGarage { get; set; }
        [Column("garageValue")]
        public double? GarageValue { get; set; }
        [Column("noRooms")]
        public short? NoRooms { get; set; }
        [Column("noBathRooms")]
        public short? NoBathRooms { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("isAvailable")]
        public bool? IsAvailable { get; set; }
        [Column("meterPrice")]
        public double? MeterPrice { get; set; }
        [Column("yearBuilt")]
        public int? YearBuilt { get; set; }
        [Column("editedBy")]
        public int? EditedBy { get; set; }

        [ForeignKey("AddedBy")]
        [InverseProperty("LocationAddedByNavigations")]
        public virtual Admin AddedByNavigation { get; set; }
        [ForeignKey("DeletedyBy")]
        [InverseProperty("Locations")]
        public virtual CustomerService DeletedyByNavigation { get; set; }
        [ForeignKey("EditedBy")]
        [InverseProperty("LocationEditedByNavigations")]
        public virtual Admin EditedByNavigation { get; set; }
        [ForeignKey("LocationTypeId")]
        [InverseProperty("Locations")]
        public virtual LocationsType LocationType { get; set; }
        [ForeignKey("PaymentTypeId")]
        [InverseProperty("Locations")]
        public virtual PaymentType PaymentType { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("Locations")]
        public virtual Project Project { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<LocationImage> LocationImages { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}