// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("projects")]
    public partial class Project
    {
        public Project()
        {
            Locations = new HashSet<Location>();
            ProjectsFeatures = new HashSet<ProjectsFeature>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("nameAr")]
        [StringLength(50)]
        public string NameAr { get; set; }
        [Column("nameEn")]
        [StringLength(50)]
        public string NameEn { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("deletedBy")]
        public int? DeletedBy { get; set; }
        [Column("deletedAt", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("address")]
        [StringLength(100)]
        public string Address { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("noUnits")]
        public int? NoUnits { get; set; }
        [Column("addedBy")]
        public int? AddedBy { get; set; }
        [Column("editedBy")]
        public int? EditedBy { get; set; }
        [Column("lastDateModified", TypeName = "datetime")]
        public DateTime? LastDateModified { get; set; }

        [ForeignKey("AddedBy")]
        [InverseProperty("ProjectAddedByNavigations")]
        public virtual Admin AddedByNavigation { get; set; }
        [ForeignKey("DeletedBy")]
        [InverseProperty("ProjectDeletedByNavigations")]
        public virtual Admin DeletedByNavigation { get; set; }
        [ForeignKey("EditedBy")]
        [InverseProperty("ProjectEditedByNavigations")]
        public virtual Admin EditedByNavigation { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<Location> Locations { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<ProjectsFeature> ProjectsFeatures { get; set; }
    }
}