// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("projects_features")]
    public partial class ProjectsFeature
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("projectId")]
        public int? ProjectId { get; set; }
        [Column("feature")]
        [StringLength(100)]
        public string Feature { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("ProjectsFeatures")]
        public virtual Project Project { get; set; }
    }
}