// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("roles_Permissions")]
    public partial class RolesPermission
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("role_Id")]
        public int? RoleId { get; set; }
        [Column("permissionId")]
        public int? PermissionId { get; set; }

        [ForeignKey("PermissionId")]
        [InverseProperty("RolesPermissions")]
        public virtual Permission Permission { get; set; }
        [ForeignKey("RoleId")]
        [InverseProperty("RolesPermissions")]
        public virtual Role Role { get; set; }
    }
}