// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("roles")]
    public partial class Role
    {
        public Role()
        {
            Admins = new HashSet<Admin>();
            RolesPermissions = new HashSet<RolesPermission>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("title")]
        [StringLength(500)]
        public string Title { get; set; }
        [Column("description")]
        [StringLength(500)]
        public string Description { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("createdBy")]
        public int? CreatedBy { get; set; }
        [Column("updatedAt", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }
        [Column("updatedBy")]
        public int? UpdatedBy { get; set; }

        [ForeignKey("CreatedBy")]
        [InverseProperty("RoleCreatedByNavigations")]
        public virtual Admin CreatedByNavigation { get; set; }
        [ForeignKey("UpdatedBy")]
        [InverseProperty("RoleUpdatedByNavigations")]
        public virtual Admin UpdatedByNavigation { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<Admin> Admins { get; set; }
        [InverseProperty("Role")]
        public virtual ICollection<RolesPermission> RolesPermissions { get; set; }
    }
}