// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("visitors")]
    public partial class Visitor
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("userName")]
        [StringLength(50)]
        public string UserName { get; set; }
        [Column("contactNameEn")]
        [StringLength(50)]
        public string ContactNameEn { get; set; }
        [Column("contactNameAr")]
        [StringLength(50)]
        public string ContactNameAr { get; set; }
        [Column("createdAt", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("isDeleted")]
        public bool? IsDeleted { get; set; }
        [Column("deletedBy")]
        public int? DeletedBy { get; set; }
        [Column("createdBy")]
        public int? CreatedBy { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("password")]
        [StringLength(100)]
        public string Password { get; set; }
        [Column("groupPermission")]
        public short? GroupPermission { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }
        [Column("mobile")]
        [StringLength(50)]
        public string Mobile { get; set; }
        [Column("secMobile")]
        [StringLength(50)]
        public string SecMobile { get; set; }

        [ForeignKey("CreatedBy")]
        [InverseProperty("Visitors")]
        public virtual CustomerService CreatedByNavigation { get; set; }
        [ForeignKey("DeletedBy")]
        [InverseProperty("Visitors")]
        public virtual User DeletedByNavigation { get; set; }
    }
}