// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("work_flow_cycle")]
    public partial class WorkFlowCycle
    {
        public WorkFlowCycle()
        {
            WorkFlowCycleAssessments = new HashSet<WorkFlowCycleAssessment>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("docId")]
        public int? DocId { get; set; }
        [Column("docType")]
        public int? DocType { get; set; }
        [Column("subject")]
        [StringLength(500)]
        public string Subject { get; set; }
        [Column("work_flow_id")]
        public int? WorkFlowId { get; set; }
        [Column("status")]
        public bool? Status { get; set; }
        [Column("sendDate", TypeName = "datetime")]
        public DateTime? SendDate { get; set; }
        [Column("lastApprovedDate", TypeName = "datetime")]
        public DateTime? LastApprovedDate { get; set; }

        [ForeignKey("WorkFlowId")]
        [InverseProperty("WorkFlowCycles")]
        public virtual WorkFlow WorkFlow { get; set; }
        [InverseProperty("Cycle")]
        public virtual ICollection<WorkFlowCycleAssessment> WorkFlowCycleAssessments { get; set; }
    }
}