// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Real_Estate_Context.Models
{
    [Table("work_flow_cycle_assessment")]
    public partial class WorkFlowCycleAssessment
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("cycleId")]
        public int? CycleId { get; set; }
        [Column("userId")]
        public int? UserId { get; set; }
        [Column("level")]
        public int? Level { get; set; }
        [Column("creationDate", TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        [Column("work_flow_contacts_id")]
        public int? WorkFlowContactsId { get; set; }
        [Column("isMultiApproval")]
        public bool? IsMultiApproval { get; set; }
        [Column("isSingleApproval")]
        public bool? IsSingleApproval { get; set; }
        [Column("autoApproved")]
        public bool? AutoApproved { get; set; }
        [Column("wasRejected")]
        public bool? WasRejected { get; set; }
        [Column("readStatus")]
        public bool? ReadStatus { get; set; }
        [Column("approvalStatus")]
        public bool? ApprovalStatus { get; set; }
        [Column("approvalDate", TypeName = "datetime")]
        public DateTime? ApprovalDate { get; set; }
        [Column("comment")]
        [StringLength(500)]
        public string Comment { get; set; }
        [Column("isDeleted")]
        public bool? IsDeleted { get; set; }
        [Column("actionByAccId")]
        public int? ActionByAccId { get; set; }

        [ForeignKey("ActionByAccId")]
        [InverseProperty("WorkFlowCycleAssessmentActionByAccs")]
        public virtual User ActionByAcc { get; set; }
        [ForeignKey("CycleId")]
        [InverseProperty("WorkFlowCycleAssessments")]
        public virtual WorkFlowCycle Cycle { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("WorkFlowCycleAssessmentUsers")]
        public virtual User User { get; set; }
        [ForeignKey("WorkFlowContactsId")]
        [InverseProperty("WorkFlowCycleAssessments")]
        public virtual WorkFlowContact WorkFlowContacts { get; set; }
    }
}